### ISSUE TITLE
Localized decimal separator not supported

### ISSUE THREAD

**Issue by bjorkert** [CustomTypeOne/LoopPatches#10] opened 2023-01-24 08:50 UTC
When entering values with "," (comma ) as decimal separator, basalLockThreshold and dosingStrategyThreshold only contains the value before the decimal separator. 
For example a basal lock 8,8 will result in 8 (mmol/l)

This happens even if locale is set on the iPhone to use comma as decimal separator.

![image](https://user-images.githubusercontent.com/12718238/214248284-f709ebab-aa21-49e1-a336-518a84b38139.png)
![image](https://user-images.githubusercontent.com/12718238/214248356-2c0edd64-f4ec-4923-8e9b-710f5557217d.png)

**Comment by marionbarker** [comment] 2023-01-24 10:31
Can you report version numbers too (and language). Do you see this for the switcher patch too with your build?

And that is way too low a number for basal lock. I hope you are just showing that as an example.

**Comment by bjorkert** [comment] 2023-01-24 10:39
Loop 3 main branch, iOS 16.2 Swedish, switcher patch added manually.

**Comment by marionbarker** [comment] 2023-01-24 10:51
Xcode version.
I meant: can you check the debugger for this behavior in switcher patch section of the code?
I will check for your response in the morning.

**Comment by bjorkert** [comment] 2023-01-24 10:55
Xcode Version 14.2 (14C18). 

The code fetching the setting is:
`let basalLockThreshold = UserDefaults.standard.double(forKey: "basalLockThreshold")`
basalLockThreshold is a string and it gets converted to double without handling localized decimal separator.

I get this behavior both in debugger and in the real looping phone.

**Comment by marionbarker** [comment] 2023-01-24 15:14
I did get someone to help me test it who uses both commas and mmol when I took over management of these patches. 

We may have just tested dosingStrategyThreshold, but I think we tested both. That's why I asked the switching portion in the middle of my night. Both dosingStrategyThreshold and basalLockThreshold use the same code prototype.

I have set up a testing configuration here and will report back. Thank you for reporting this and opening an issue.

**Comment by marionbarker** [comment] 2023-01-24 15:49
I don't know why it is behaving differently now that when we tested earlier but I am getting the same results.

I will modify the warnings I placed in the README file and in the [Loop and Learn Customization](https://www.loopandlearn.org/github-lnl-patches/) page to indicate that mmol/L users should use a period instead of a comma in their entries for threshold in LoopPatches.

**Comment by marionbarker** [comment] 2023-01-24 15:50
I will leave this issue open. I don't have a solution, only a work-around.

**Comment by marionbarker** [comment] 2023-01-24 15:56
Can you confirm that using a period gives you the threshold value you want?

**Comment by bjorkert** [comment] 2023-01-24 16:23
Period works fine:
![image](https://user-images.githubusercontent.com/12718238/214348981-2bbad6f3-eed8-409c-abee-cbfa210dcff0.png)
![image](https://user-images.githubusercontent.com/12718238/214349033-ca5c4b61-495c-47ac-bb8d-9b6a1a795175.png)

**Comment by bjorkert** [comment] 2023-01-24 16:32
It could be something like this, but perhaps not a one-liner and with error handling... 
let basalLockThreshold = Double(string: UserDefaults.standard.string(forKey: "basalLockThreshold"), using: Locale.current)

Since users will now have period even if it is not their locale, a plain replacement of "," to "." would probably do.

**Comment by hummelstrand** [comment] 2023-01-24 17:37
@marionbarker I can confirm @bjorkert’s finding. I believe you and me tested with Basal Lock set to “10,0” which would explain why it appeared to be working correctly.

**Comment by marionbarker** [comment] 2023-01-24 17:46
There is not much in the way of error handling or guardrails for these patch thresholds, which makes me a bit nervous. Thanks so much for paying attention. At this point, I think I'll leave the decimal point requirement in the iOS settings. No promises on future improvements. But I'll keep this in mind.

And yes @hummelstrand - that's what I was thinking. I was concerned if it worked in mmol/L at all, because that was not something I could test.

**Comment by marionbarker** [comment] 2023-04-16 22:52
Closing this. We have documented that the format must be 13.8 and not 13,8 for threshold values.

**Closed as completed by marionbarker** 2023-04-16 22:52 UTC
